[package]
name = "poti"
version = "0.1.0"
edition = "2024"

[dependencies]
choki = "1.1.14"
lazy_static = "1.5.0"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
